# Generated by Django 3.2.8 on 2021-11-11 09:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=50)),
                ('productprice', models.IntegerField(max_length=4)),
                ('deadline', models.DateTimeField(default=datetime.datetime(2021, 11, 11, 9, 29, 55, 446882, tzinfo=utc))),
            ],
        ),
    ]
