# Generated by Django 3.2.9 on 2021-11-12 08:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='productimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='seller',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 8, 16, 41, 636810, tzinfo=utc)),
        ),
    ]
