# Generated by Django 3.2.9 on 2021-11-13 05:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20211112_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 13, 5, 21, 18, 507417, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='seller',
            name='productimage',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='seller',
            name='productprice',
            field=models.IntegerField(max_length=7),
        ),
    ]
