# Generated by Django 3.2.6 on 2021-11-14 15:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seller', '0004_auto_20211113_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 14, 15, 42, 9, 713946, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='seller',
            name='productimage',
            field=models.ImageField(upload_to=''),
        ),
        migrations.CreateModel(
            name='bidding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidamount', models.IntegerField(max_length=7)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
